apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/mydb
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdA==          # base64 de "root"
  db-username: cm9vdA==            # base64 de "root"
  db-password: cm9vdA==            # base64 de "root"